version: 0.2

phases:
  build:
    commands:
      - echo "Target URL: $TARGET_URL"
      - echo "Running OWASP ZAP baseline scan against $TARGET_URL..."
      - docker run --rm -t owasp/zap2docker-stable zap-baseline.py -t "$TARGET_URL" -m 5 -r zap_report.html

artifacts:
  files:
    - zap_report.html
  discard-paths: yes
