version: 0.2
phases:
  build:
    commands:
      - echo "Logging into Docker Hub..."
      - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - echo "Target URL: $TARGET_URL"
      - echo "Running OWASP ZAP baseline scan..."
      - |
        set +e
        docker run --rm -v $(pwd):/zap/wrk -t zaproxy/zap-stable zap-baseline.py -t "$TARGET_URL" -m 5 -r zap_report.html
        EXIT_CODE=$?
        echo "ZAP exit code: $EXIT_CODE"
        if [ ! -f zap_report.html ]; then
          echo "ZAP scan failed or DockerHub rate limit reached" > zap_report.html
        fi
        set -e
artifacts:
  files:
    - zap_report.html
  discard-paths: yes
