version: 0.2
phases:
  install:
    commands:
      - echo "Install Docker for OWASP ZAP DAST (using CodeBuild standard image with docker)"
  pre_build:
    commands:
      - echo "Target URL: $TARGET_URL"
  build:
    commands:
      - echo "Running OWASP ZAP baseline scan..."
      - docker run --rm -t owasp/zap2docker-stable zap-baseline.py -t "$TARGET_URL" -m 5
artifacts:
  files:
    - '**/*'
  discard-paths: yes
